PORTNAME=			anime-fetch
DISTVERSION=		0.0.0
CATEGORIES=			sysutils

MAINTAINER=			xgui4-dev@example.com
COMMENT=			A noefetch-inspired utility that fetch you system info with a OS-Tan. 
WWW=				https://github.com/xgui4/anime-fetch

LICENSE=			GPLv3
LICENSE_FILE=		${WRKSRC}/LICENSE.md

BUILD_DEPENDS=		
LIB_DEPENDS=		
RUN_DEPENDS=		

USES=				cmake pkgconfig
USE_GITHUB=			yes
GH_PROJECT=			anime-fetch
GH_ACCOUNT=			xgui4
GH_TAGNAME= 		7056ea23b75da380d65aeb15385c3a704cd7684f

.include <bsd.port.mk>